default_stages: [push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        name: Validate YAML files
        exclude: conda/recipe/meta.yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.10.1
    hooks:
      - id: validate-pyproject
        name: Validate pyproject.toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff
        stages: [commit]
      - id: ruff-format
        stages: [commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
      - id: mypy
        language: system

  # TODO: add pytest-cov

  # export python requirements
  - repo: https://github.com/pdm-project/pdm
    rev: 2.x.y # a PDM release exposing the hook
    hooks:
      - id: pdm-export
        # command arguments, e.g.:
        args: [ '-o', 'requirements.txt', '--without-hashes' ]
        files: ^pdm.lock$

  - repo: https://github.com/pdm-project/pdm
    rev: 2.x.y # a PDM release exposing the hook
    hooks:
      - id: pdm-lock-check