---
# Install pre-commit hooks via
# pre-commit install
ci:
  autofix_prs: false
  autoupdate_schedule: 'quarterly'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [svg]
        exclude: |
          (?x)^(
            CHANGELOG |
            docs/source/generated |
            docs/source/fr_metrics/generated |
            docs/source/nr_metrics/generated
          )
      - id: end-of-file-fixer
        exclude_types: [svg]
        exclude: |
          (?x)^(
            CHANGELOG |
            docs/source/generated |
            docs/source/fr_metrics/generated |
            docs/source/nr_metrics/generated
          )
      - id: debug-statements
      - id: check-ast
      - id: mixed-line-ending
      - id: name-tests-test
        args: ["--pytest-test-first"]
      - id: check-yaml
        exclude: conda/recipe/meta.yaml
        args: [--allow-multiple-documents, --unsafe]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.7
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.10.1
    hooks:
      - id: validate-pyproject
        name: Validate pyproject.toml

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.17.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/rstcheck/rstcheck
    rev: v6.2.4
    hooks:
      - id: rstcheck
        additional_dependencies:
          - sphinx>=1.8.1

  - repo: https://github.com/thclark/pre-commit-sphinx
    rev: 0.0.3
    hooks:
      - id: build-docs
        additional_dependencies:
          - viqa[docs]
        args: ['--cache-dir', 'docs/build/doctrees', '--html-dir', 'docs/build/html', '--source-dir', 'docs/source']
        language_version: python3
        stages: [push]

  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.1
    hooks:
      - id: actionlint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["--strict", "--config-file=.yamllint.yaml"]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        files: ^.*\.(py|c|cpp|h|m|md|rst|yml|yaml)$
        exclude: |
          (?x)^(
          CHANGELOG |
          CODE_OF_CONDUCT
          )

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies:
          - viqa[lint]
        args: ["--config-file=pyproject.toml", "src/viqa"]
        files: src/viqa  # Only run when files in src/viqa are changed.
        pass_filenames: false
