---
name: Lint
run-name: Linting and Type-Checking

on:
  workflow_call:

permissions:
  contents: read

jobs:
  Lint:
    runs-on: ubuntu-latest
    concurrency: Lint

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ vars.MINIMAL_PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ vars.MINIMAL_PYTHON_VERSION }}

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ruff Check
        id: ruff
        uses: astral-sh/ruff-action@v1.1.1
        with:
          args: "check --config pyproject.toml"
          src: './src/viqa'

      - name: Ruff Format Check
        id: ruff-format
        uses: astral-sh/ruff-action@v1.1.1
        with:
          args: "format --check --config pyproject.toml"
          src: './src/viqa'

# - name: Mypy
#   id: mypy
#   uses: python/mypy@v1.13.0
#   with:
#     options: "--config-file=pyproject.toml"
#     paths: "src/viqa"
#     install_project_dependencies: 'no'
